/* ============================================================================
   POSTGRES INIT DB — MeterWorklog (MWL) / MWLTimesheet
   ============================================================================
   Straight syntax conversion of this repo's current MSSQL schema dump
   (previously the content of this file) into PostgreSQL DDL. Table shapes,
   column order, defaults, and constraints are preserved 1:1 from the source;
   only MSSQL-specific syntax is translated:

     - int identity                    -> INTEGER GENERATED BY DEFAULT AS IDENTITY
     - nvarchar(n) / nchar(n) / char   -> VARCHAR(n) / CHAR(n) / CHAR(1)
       (Postgres text types are UTF-8 natively; there is no separate
       "national character" type to map to)
     - datetime / datetime2            -> TIMESTAMP
     - getdate() / getdate() default   -> now() / CURRENT_DATE (for the DATE column)
     - bit                             -> BOOLEAN (0/1 -> FALSE/TRUE)
     - named MSSQL DEFAULT/PK/FK constraint identifiers (e.g. DF_Allowance_date,
       PK__Employee__...) are dropped where Postgres doesn't need them to be
       named; the one CHECK constraint whose name is referenced elsewhere in
       this repo's tooling (CK__worklogs__status__534D60F1) is preserved.
     - computed columns (`hours`, `overtime_hours`, `regular_hours` on
       worklogs) using DATEDIFF(MINUTE, a, b) are translated to
       EXTRACT(EPOCH FROM (b - a)) / 60.0, using GENERATED ALWAYS AS (...) STORED
       in place of MSSQL's PERSISTED computed column.

   All identifiers are double-quoted to preserve exact MSSQL casing
   (e.g. "EmployeeID", "CreateAt") — remember every reference in application
   SQL must use the same quoting, since unquoted identifiers fold to
   lowercase in Postgres.

   SCOPE: schema only — no seed/data rows. Tables are created in FK-dependency
   order (members/Employee/projects before users, users before
   file_folders/files/security_events/user_security_state/worklogs).

   REQUIRES: PostgreSQL 12+ (GENERATED ALWAYS AS ... STORED) and
   PostgreSQL 10+ (GENERATED ... AS IDENTITY). Not yet exercised against a
   running Postgres instance — verify the worklogs generated columns with a
   test row (start_time='08:00', end_time='17:30' should give hours=8.00,
   overtime_hours=0.00, regular_hours=8.00) before trusting this in prod.
============================================================================ */

BEGIN;

/* =========================
   ALLOWANCE
========================= */
CREATE TABLE IF NOT EXISTS "Allowance" (
    "ID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "log_date"    DATE DEFAULT CURRENT_DATE,
    "EmployeeID"  CHAR(5),
    "ProjectCode" CHAR(30),
    "Description" CHAR(500),
    "type"        CHAR(1),
    "CreateAt"    TIMESTAMP DEFAULT now(),
    "UpdateAt"    TIMESTAMP DEFAULT now(),
    "IsEditRow"   BOOLEAN DEFAULT TRUE
);

/* =========================
   EMPLOYEE
========================= */
CREATE TABLE IF NOT EXISTS "Employee" (
    "ID"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID"      VARCHAR(5)   NOT NULL,
    "EmployeeName"    VARCHAR(150) NOT NULL,
    "Department"      VARCHAR(100),
    "Position"        VARCHAR(100),
    "Level"           VARCHAR(10),
    "JG"              VARCHAR(20),
    "CreateAt"        TIMESTAMP DEFAULT now(),
    "UpdateAt"        TIMESTAMP DEFAULT now(),
    "AvatarPath"      VARCHAR(300),
    "AvatarMime"      VARCHAR(100),
    "AvatarUpdatedAt" TIMESTAMP,
    "Operation"       VARCHAR(50)
);

/* =========================
   PROJECT AND BUDGET
========================= */
CREATE TABLE IF NOT EXISTS "ProjectAndBudget" (
    "ID"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectCode"       CHAR(50),
    "Budget"            CHAR(50),
    "Description"       CHAR(500),
    "CreateAt"          TIMESTAMP DEFAULT now(),
    "UpdateAt"          TIMESTAMP DEFAULT now(),
    "Status"            VARCHAR(20) DEFAULT 'Initiative',
    "ProjectDepartment" VARCHAR(20)
);

/* =========================
   HOLIDAY
   NOTE: "ID" is NOT auto-incrementing in the source schema — inserts must
   supply an explicit ID, same as the MSSQL original.
========================= */
CREATE TABLE IF NOT EXISTS "holiday" (
    "ID"          INTEGER PRIMARY KEY,
    "date"        DATE,
    "description" CHAR(200)
);

/* =========================
   MEMBERS (legacy, kept for FK compatibility — see CLAUDE.md §4)
========================= */
CREATE TABLE IF NOT EXISTS "members" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       VARCHAR(200) NOT NULL,
    "department" VARCHAR(100),
    "staff_id"   VARCHAR(50)
);

/* =========================
   MEMBER SKILLS
========================= */
CREATE TABLE IF NOT EXISTS "member_skills" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"  INTEGER,
    "name"       VARCHAR(120) NOT NULL,
    "level"      SMALLINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
    "EmployeeID" VARCHAR(5),
    CONSTRAINT "CK_member_skills_level" CHECK ("level" BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS "IX_member_skills_employee" ON "member_skills" ("EmployeeID");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_member_skills_employee_name"
    ON "member_skills" ("EmployeeID", "name")
    WHERE "EmployeeID" IS NOT NULL;

/* =========================
   PROJECTS
========================= */
CREATE TABLE IF NOT EXISTS "projects" (
    "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"            VARCHAR(200) NOT NULL,
    "main_members"    TEXT,
    "support_members" TEXT,
    "Description"     CHAR(500),
    CONSTRAINT "UQ_projects_name" UNIQUE ("name")
);

/* =========================
   SETTINGS
========================= */
CREATE TABLE IF NOT EXISTS "settings" (
    "key"   VARCHAR(100) PRIMARY KEY,
    "value" TEXT NOT NULL
);

/* =========================
   USERS (must precede security tables / self-FK on reviewed_by)
========================= */
CREATE TABLE IF NOT EXISTS "users" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"      VARCHAR(100) NOT NULL,
    "password_hash" VARCHAR(256) NOT NULL,
    "role"          VARCHAR(50)  NOT NULL DEFAULT 'Staff',
    "member_id"     INTEGER REFERENCES "members"("id"),
    "EmployeeID"    INTEGER,
    "status"        VARCHAR(20)  NOT NULL DEFAULT 'Active',
    "reviewed_by"   INTEGER REFERENCES "users"("id"),
    "reviewed_at"   TIMESTAMP DEFAULT now(),
    "created_at"    TIMESTAMP DEFAULT now(),
    "email"         VARCHAR(255),
    CONSTRAINT "UQ_users_username" UNIQUE ("username"),
    CONSTRAINT "CK_users_role"   CHECK ("role" IN ('Super_Ultimate_ADMIN','Admin','Leader','Staff')),
    CONSTRAINT "CK_users_status" CHECK ("status" IN ('Declined','Active','Pending'))
);

/* =========================
   FILE SHARE
========================= */
CREATE TABLE IF NOT EXISTS "file_folders" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(200) NOT NULL,
    "parent_id"     INTEGER REFERENCES "file_folders"("id"),
    "created_by"    INTEGER REFERENCES "users"("id"),
    "created_at"    TIMESTAMP DEFAULT now(),
    "is_classified" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "UQ_file_folders_parent_name" UNIQUE ("parent_id", "name")
);

CREATE TABLE IF NOT EXISTS "files" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "folder_id"     INTEGER REFERENCES "file_folders"("id"),
    "original_name" VARCHAR(400) NOT NULL,
    "stored_name"   VARCHAR(200) NOT NULL,
    "size_bytes"    BIGINT NOT NULL,
    "mime_type"     VARCHAR(200),
    "sha256"        CHAR(64),
    "uploaded_by"   INTEGER REFERENCES "users"("id"),
    "uploaded_at"   TIMESTAMP DEFAULT now(),
    "is_classified" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "UQ_files_stored_name" UNIQUE ("stored_name")
);

CREATE INDEX IF NOT EXISTS "IX_files_folder" ON "files" ("folder_id");

/* =========================
   SECURITY EVENTS
========================= */
CREATE TABLE IF NOT EXISTS "security_events" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"    INTEGER REFERENCES "users"("id"),
    "username"   VARCHAR(100),
    "event_type" VARCHAR(100) NOT NULL,
    "ip_address" VARCHAR(100),
    "user_agent" VARCHAR(500),
    "detail"     TEXT,
    "created_at" TIMESTAMP DEFAULT now()
);

/* =========================
   USER SECURITY STATE
========================= */
CREATE TABLE IF NOT EXISTS "user_security_state" (
    "user_id"                   INTEGER PRIMARY KEY REFERENCES "users"("id"),
    "failed_login_count"        INTEGER NOT NULL DEFAULT 0,
    "failed_login_window_start" TIMESTAMP,
    "locked_until"              TIMESTAMP,
    "unlock_token_hash"         VARCHAR(256),
    "unlock_token_expires_at"   TIMESTAMP,
    "last_unlock_email_sent_at" TIMESTAMP,
    "updated_at"                TIMESTAMP NOT NULL DEFAULT now(),
    "reset_token_hash"          VARCHAR(64),
    "reset_token_expires_at"    TIMESTAMP,
    "last_reset_email_sent_at"  TIMESTAMP
);

/* =========================
   WORKLOGS
========================= */
CREATE TABLE IF NOT EXISTS "worklogs" (
    "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"         INTEGER REFERENCES "members"("id"),
    "EmployeeID"        VARCHAR(5),
    "log_date"          DATE NOT NULL,
    "project"           VARCHAR(200),
    "ProjectDepartment" VARCHAR(20),
    "task"              VARCHAR(500),
    "start_time"        TIME,
    "end_time"          TIME,

    -- hours: (end - start) minus lunch overlap (12:00-13:00).
    "hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL AND "end_time" >= "start_time"
            THEN (
                EXTRACT(EPOCH FROM ("end_time" - "start_time")) / 60.0
                - CASE
                    WHEN "start_time" < TIME '13:00:00' AND "end_time" > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '13:00:00') - GREATEST("start_time", TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            )::NUMERIC(5,2)
        END
    ) STORED,

    -- overtime_hours: minutes before 08:30 plus minutes after 17:30.
    "overtime_hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL AND "end_time" >= "start_time"
            THEN (
                (CASE WHEN "start_time" < TIME '08:30:00'
                      THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '08:30:00') - "start_time")) / 60.0
                      ELSE 0 END)
                +
                (CASE WHEN "end_time" > TIME '17:30:00'
                      THEN EXTRACT(EPOCH FROM ("end_time" - GREATEST("start_time", TIME '17:30:00'))) / 60.0
                      ELSE 0 END)
            )::NUMERIC(5,2)
        END
    ) STORED,

    "status" VARCHAR(50)
        CONSTRAINT "CK__worklogs__status__534D60F1"
        CHECK ("status" IN ('Man day', 'Pending', 'In Progress', 'Done', 'Leave')),
    "note"   VARCHAR(1000),

    "OT1"   NUMERIC(18,2),
    "OT3"   NUMERIC(18,2),
    "OT1_5" NUMERIC(18,2),

    "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now(),

    "Description" CHAR(500),
    "IsEditRow"   BOOLEAN DEFAULT TRUE,

    -- regular_hours: portion of work inside 08:30-17:30 minus lunch overlap.
    "regular_hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL
                 AND "end_time" > TIME '08:30:00' AND "start_time" < TIME '17:30:00'
            THEN (
                EXTRACT(EPOCH FROM (LEAST("end_time", TIME '17:30:00') - GREATEST("start_time", TIME '08:30:00'))) / 60.0
                - CASE
                    WHEN "start_time" < TIME '13:00:00' AND "end_time" > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '13:00:00') - GREATEST("start_time", TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            )::NUMERIC(5,2)
            ELSE 0
        END
    ) STORED,

    "is_allowance"       BOOLEAN NOT NULL DEFAULT FALSE,
    "allowance_overtime" NUMERIC(18,2) DEFAULT 0.00
);

CREATE INDEX IF NOT EXISTS "IX_worklogs_employee_date" ON "worklogs" ("EmployeeID", "log_date");

COMMIT;

INSERT INTO users (username, password_hash, role, status, "EmployeeID")
VALUES (
           'sultadkukkuk',
           'scrypt:32768:8:1$6BpoyyNeineDbHF7$ab9ef6ceb57ba1a3bebe67b798313a149be239686efbe3a622421b287884b61232151accc1ee2b30bed04b6a85e688ab65544354fb434bad28641d650e01145d',
           'Super_Ultimate_ADMIN','Active','11111'
       )
ON CONFLICT (username) DO NOTHING;
