/* ============================================================================
   POSTGRES INIT DB — MeterWorklog (MWL)
   ============================================================================
   Applied automatically by db._init_db_postgres() when DB_ENGINE=postgres.
   The whole file is sent as ONE simple query under autocommit, so Postgres
   wraps it in a single implicit transaction: it either all applies or none of
   it does. Do NOT add BEGIN/COMMIT here.

   Idempotency comes from IF NOT EXISTS + "INSERT ... WHERE NOT EXISTS", not
   from a transaction wrapper.

   -- Identifier casing ---------------------------------------------------
   Every identifier is UNQUOTED and lowercase, so Postgres folds application
   SQL like `w.EmployeeID` down to `employeeid` and it matches. Result-set keys
   that the frontend depends on are restored with double-quoted aliases in the
   application SQL (`SELECT employeeid AS "EmployeeID"`), which works on both
   engines. Never add a quoted mixed-case identifier to this file.

   -- Source of truth ------------------------------------------------------
   Column names, lengths, nullability and defaults mirror the LIVE MSSQL
   `MeterWorklog` database (introspected via sys.columns), not init_db.sql --
   the two had drifted. Deliberate departures from the MSSQL source:

     nchar/char(n)  -> varchar(n)   MSSQL blank-pads CHAR and then ignores the
                                    padding in comparisons; Postgres keeps the
                                    padding and it leaks into JSON responses
                                    and breaks joins such as
                                    `pb.description = w.description`.
     EmployeeID     -> varchar(5)   Live MSSQL stores it as INT on worklogs /
                                    users / member_skills but as NVARCHAR(5) on
                                    employee, and relies on implicit conversion
                                    to join them. Postgres has no such
                                    conversion (42883: operator does not exist:
                                    integer = character varying), so all the
                                    tables are normalised to the authoritative
                                    employee.employeeid type. Every stored ID
                                    is a 5-digit numeric with no leading zero,
                                    so the int -> text migration is lossless.
     bit            -> boolean
     datetime2      -> timestamp
     nvarchar(max)  -> text
     computed cols  -> GENERATED ALWAYS AS (...) STORED, with
                       DATEDIFF(MINUTE,a,b) rewritten as
                       EXTRACT(EPOCH FROM (b - a)) / 60.0

   worklogs.status additionally accepts 'Leave', which app/worklogs.py has
   allowed since VALID_STATUSES was extended but the live MSSQL CHECK
   constraint still rejects. init_db.sql carries a matching fix.

   REQUIRES: PostgreSQL 12+ (GENERATED ... STORED), 11+ (INCLUDE indexes).
============================================================================ */

CREATE SCHEMA IF NOT EXISTS mwlts;

-- db.py sets search_path from PG_SCHEMA at connect time. When running this
-- file by hand (psql / WebStorm console), run `SET search_path TO mwlts;`
-- first or every object below lands in public.

/* =========================
   ALLOWANCE
========================= */
CREATE TABLE IF NOT EXISTS allowance (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date    DATE         NOT NULL,
    employeeid  VARCHAR(50)  NOT NULL,
    projectcode VARCHAR(50),
    description VARCHAR(255),
    type        VARCHAR(50),
    createat    TIMESTAMP DEFAULT now(),
    updateat    TIMESTAMP DEFAULT now(),
    iseditrow   BOOLEAN   DEFAULT TRUE
);

/* =========================
   EMPLOYEE — authoritative HR directory
========================= */
CREATE TABLE IF NOT EXISTS employee (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeid      VARCHAR(5)   NOT NULL,
    employeename    VARCHAR(150) NOT NULL,
    department      VARCHAR(100),
    position        VARCHAR(100),
    level           VARCHAR(10),
    jg              VARCHAR(20),
    createat        TIMESTAMP DEFAULT now(),
    updateat        TIMESTAMP DEFAULT now(),
    avatarpath      VARCHAR(300),
    avatarmime      VARCHAR(100),
    avatarupdatedat TIMESTAMP
);

/* =========================
   PROJECT AND BUDGET
   Read-only for the app: projects.py lists it, worklogs.py/allowance.py map
   a project name (description) to a projectcode. No app code writes here.
========================= */
CREATE TABLE IF NOT EXISTS projectandbudget (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projectcode       VARCHAR(20),
    budgetcode        VARCHAR(20),
    description       VARCHAR(200),
    projectdepartment VARCHAR(10),
    status            VARCHAR(15)
);

/* =========================
   HOLIDAY
   id is not auto-assigned in the MSSQL source; GENERATED BY DEFAULT keeps
   explicit-id inserts working while still allowing the column to be omitted.
========================= */
CREATE TABLE IF NOT EXISTS holiday (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        DATE,
    description VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS ix_holiday_date ON holiday (date);

/* =========================
   MEMBERS (legacy, kept for FK compatibility — see CLAUDE.md §4)
========================= */
CREATE TABLE IF NOT EXISTS members (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    department VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    staff_id   VARCHAR(100),
    position   VARCHAR(200)
);

/* =========================
   MEMBER SKILLS
   No FK on member_id: the EmployeeID migration deliberately dropped it
   (init_db.sql) because skills are keyed by employeeid now.
========================= */
CREATE TABLE IF NOT EXISTS member_skills (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  INTEGER,
    name       VARCHAR(120) NOT NULL,
    level      SMALLINT     NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at TIMESTAMP    NOT NULL DEFAULT now(),
    employeeid VARCHAR(5),
    CONSTRAINT ck_member_skills_level CHECK (level BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS ix_member_skills_member   ON member_skills (member_id);
CREATE INDEX IF NOT EXISTS ix_member_skills_employee ON member_skills (employeeid);

CREATE UNIQUE INDEX IF NOT EXISTS ux_member_skills_employee_name
    ON member_skills (employeeid, name)
    WHERE employeeid IS NOT NULL;

/* =========================
   PROJECTS
   main_members / support_members hold JSON arrays of EmployeeIDs.
========================= */
CREATE TABLE IF NOT EXISTS projects (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    main_members    TEXT,
    support_members TEXT,
    description     VARCHAR(300),
    CONSTRAINT uq_projects_name UNIQUE (name)
);

/* =========================
   SETTINGS
========================= */
CREATE TABLE IF NOT EXISTS settings (
    key   VARCHAR(100) PRIMARY KEY,
    value TEXT NOT NULL
);

/* =========================
   USERS (must precede the security tables and the reviewed_by self-FK)
========================= */
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'Staff',
    member_id     INTEGER REFERENCES members (id),
    created_at    TIMESTAMP DEFAULT now(),
    status        VARCHAR(20)  NOT NULL DEFAULT 'Active',
    reviewed_by   INTEGER REFERENCES users (id),
    reviewed_at   TIMESTAMP,
    employeeid    VARCHAR(5),
    email         VARCHAR(255),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role   CHECK (role   IN ('Super_Ultimate_ADMIN','Admin','Leader','Staff')),
    CONSTRAINT ck_users_status CHECK (status IN ('Declined','Active','Pending'))
);

CREATE INDEX IF NOT EXISTS ix_users_status ON users (status);

/* =========================
   FILE SHARE
========================= */
CREATE TABLE IF NOT EXISTS file_folders (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    parent_id     INTEGER REFERENCES file_folders (id),
    created_by    INTEGER REFERENCES users (id),
    created_at    TIMESTAMP DEFAULT now(),
    is_classified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_file_folders_parent_name UNIQUE (parent_id, name)
);

CREATE INDEX IF NOT EXISTS ix_file_folders_parent_name
    ON file_folders (parent_id, name);

CREATE TABLE IF NOT EXISTS files (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id     INTEGER REFERENCES file_folders (id),
    original_name VARCHAR(400) NOT NULL,
    stored_name   VARCHAR(200) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    mime_type     VARCHAR(200),
    sha256        VARCHAR(64),
    uploaded_by   INTEGER REFERENCES users (id),
    uploaded_at   TIMESTAMP DEFAULT now(),
    is_classified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_files_stored_name UNIQUE (stored_name)
);

CREATE INDEX IF NOT EXISTS ix_files_folder ON files (folder_id);

/* =========================
   SECURITY EVENTS
========================= */
CREATE TABLE IF NOT EXISTS security_events (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER REFERENCES users (id),
    username   VARCHAR(100),
    event_type VARCHAR(100) NOT NULL,
    ip_address VARCHAR(100),
    user_agent VARCHAR(500),
    detail     TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

/* =========================
   USER SECURITY STATE
========================= */
CREATE TABLE IF NOT EXISTS user_security_state (
    user_id                   INTEGER PRIMARY KEY REFERENCES users (id),
    failed_login_count        INTEGER NOT NULL DEFAULT 0,
    failed_login_window_start TIMESTAMP,
    locked_until              TIMESTAMP,
    unlock_token_hash         VARCHAR(256),
    unlock_token_expires_at   TIMESTAMP,
    last_unlock_email_sent_at TIMESTAMP,
    updated_at                TIMESTAMP NOT NULL DEFAULT now(),
    reset_token_hash          VARCHAR(64),
    reset_token_expires_at    TIMESTAMP,
    last_reset_email_sent_at  TIMESTAMP
);

/* =========================
   WORKLOGS
========================= */
CREATE TABLE IF NOT EXISTS worklogs (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         INTEGER REFERENCES members (id),
    employeeid        VARCHAR(5),
    log_date          DATE NOT NULL,
    project           VARCHAR(200),
    projectdepartment VARCHAR(50),
    task              VARCHAR(500),
    start_time        TIME,
    end_time          TIME,

    -- hours: (end - start) minus the 12:00-13:00 lunch overlap.
    hours NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN start_time IS NOT NULL AND end_time IS NOT NULL AND end_time >= start_time
            THEN (
                EXTRACT(EPOCH FROM (end_time - start_time)) / 60.0
                - CASE
                    WHEN start_time < TIME '13:00:00' AND end_time > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST(end_time, TIME '13:00:00')
                                             - GREATEST(start_time, TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            ) / 60.0
        END
    ) STORED,

    -- overtime_hours: minutes before 08:30 plus minutes after 17:30.
    overtime_hours NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN start_time IS NOT NULL AND end_time IS NOT NULL AND end_time >= start_time
            THEN (
                (CASE WHEN start_time < TIME '08:30:00'
                      THEN EXTRACT(EPOCH FROM (LEAST(end_time, TIME '08:30:00') - start_time)) / 60.0
                      ELSE 0 END)
                +
                (CASE WHEN end_time > TIME '17:30:00'
                      THEN EXTRACT(EPOCH FROM (end_time - GREATEST(start_time, TIME '17:30:00'))) / 60.0
                      ELSE 0 END)
            ) / 60.0
        END
    ) STORED,

    status VARCHAR(50)
        CONSTRAINT ck_worklogs_status
        CHECK (status IN ('Man day', 'Pending', 'In Progress', 'Done', 'Leave')),
    note   VARCHAR(1000),

    ot1   NUMERIC(5,2),
    ot3   NUMERIC(5,2),
    ot1_5 NUMERIC(5,2),

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),

    description VARCHAR(200),
    iseditrow   BOOLEAN NOT NULL DEFAULT TRUE,

    -- regular_hours: the 08:30-17:30 portion of the entry, minus lunch overlap.
    regular_hours NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN start_time IS NOT NULL AND end_time IS NOT NULL
                 AND end_time > TIME '08:30:00' AND start_time < TIME '17:30:00'
            THEN (
                EXTRACT(EPOCH FROM (LEAST(end_time, TIME '17:30:00')
                                    - GREATEST(start_time, TIME '08:30:00'))) / 60.0
                - CASE
                    WHEN start_time < TIME '13:00:00' AND end_time > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST(end_time, TIME '13:00:00')
                                             - GREATEST(start_time, TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            ) / 60.0
            ELSE 0
        END
    ) STORED,

    is_allowance       BOOLEAN NOT NULL DEFAULT FALSE,
    allowance_overtime NUMERIC(5,2)
);

CREATE INDEX IF NOT EXISTS ix_worklogs_employee_date
    ON worklogs (employeeid, log_date);

CREATE INDEX IF NOT EXISTS ix_worklogs_project
    ON worklogs (project)
    WHERE project IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_worklogs_log_date
    ON worklogs (log_date)
    INCLUDE (employeeid, project, status);

/* =========================
   SEED DATA
========================= */
INSERT INTO settings (key, value)
SELECT 'worklog_open', '0'
WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key = 'worklog_open');

INSERT INTO projects (name)
SELECT 'Warehouse'
WHERE NOT EXISTS (SELECT 1 FROM projects WHERE name = 'Warehouse');

INSERT INTO members (name, department)
SELECT 'Boonyarith Akkarasongthum', 'Meter'
WHERE NOT EXISTS (SELECT 1 FROM members WHERE name = 'Boonyarith Akkarasongthum');

INSERT INTO users (username, password_hash, role, status, employeeid)
VALUES (
    'sultadkukkuk',
    'scrypt:32768:8:1$6BpoyyNeineDbHF7$ab9ef6ceb57ba1a3bebe67b798313a149be239686efbe3a622421b287884b61232151accc1ee2b30bed04b6a85e688ab65544354fb434bad28641d650e01145d',
    'Super_Ultimate_ADMIN', 'Active', '11111'
)
ON CONFLICT (username) DO NOTHING;

-- parent_id IS NULL is the implicit root; 'Shared' is a convenient subfolder.
INSERT INTO file_folders (name, parent_id)
SELECT 'Shared', NULL
WHERE NOT EXISTS (
    SELECT 1 FROM file_folders WHERE parent_id IS NULL AND name = 'Shared'
);
