/* ============================================================================
   POSTGRES INIT DB — MeterWorklog (MWL) / MWLTimesheet
   ============================================================================
   Generated by live-inspecting the production MSSQL instance:
     DB_SERVER=26.169.179.89  DB_NAME=MWLTimesheet  (SQL Server 2017 Express)
   via sys.tables / sys.columns / sys.indexes / sys.foreign_keys /
   sys.check_constraints, cross-referenced against init_db.sql in this repo.

   IMPORTANT — this mirrors the LIVE production schema, not just init_db.sql.
   The live database has drifted from init_db.sql in several places (columns
   added directly against prod, types changed, constraints missing). Every
   place this file differs from init_db.sql is called out with a "DRIFT:"
   comment at the point of divergence. Summary:

     1. dbo.Employee has an extra "Operation" NVARCHAR(100) column not in
        init_db.sql.
     2. dbo.projects has an extra "Description" CHAR(500) column not in
        init_db.sql.
     3. dbo.worklogs:
        - status CHECK now allows 5 values (adds 'Leave'); init_db.sql only
          documents 4 ('Done','In Progress','Pending','Man day').
        - status column is NVARCHAR(100) live vs NVARCHAR(50) as originally
          declared.
        - ProjectDepartment is NVARCHAR(20) live vs NVARCHAR(100) as the
          ALTER in init_db.sql declares.
        - Description is CHAR(500) live vs NVARCHAR(500) as the ALTER
          declares.
        - IsEditRow is NULLable live vs NOT NULL as the ALTER declares.
        - OT1 / OT3 / OT1_5 / allowance_overtime are DECIMAL(18,2) live vs
          DECIMAL(5,2) as the ALTERs declare.
     4. dbo.file_folders and dbo.files both have an "is_classified" BIT NOT
        NULL DEFAULT 0 column live that init_db.sql never creates (it backs
        the classified-file feature described in CLAUDE.md §7b but the
        ALTER TABLE was applied directly to prod and never checked in).
     5. dbo.users.EmployeeID is INT live, NOT NVARCHAR(5) as init_db.sql
        declares — every other EmployeeID column in the schema (Employee,
        worklogs, member_skills) is a VARCHAR business key. This is a real
        type inconsistency worth fixing at the application layer; this
        migration preserves it as-is (INTEGER) to match production exactly.
     6. dbo.holiday live table:
        - "ID" is NOT an IDENTITY column in production (inserts must supply
          an explicit ID) despite init_db.sql declaring IDENTITY(1,1).
        - "date" is nullable live with NO unique constraint, despite
          init_db.sql declaring `DATE NOT NULL UNIQUE`.
        - "description" is CHAR(200) live vs NVARCHAR(500) declared.
     7. dbo.Allowance live table diverges heavily from init_db.sql's
        declared CREATE TABLE: log_date is nullable, EmployeeID is CHAR(5)
        (not VARCHAR(50) NOT NULL), ProjectCode is NCHAR(30) (not
        VARCHAR(50)), Description is NCHAR(500) (not VARCHAR(255)), type is
        CHAR(1) (not VARCHAR(50)), and CreateAt/UpdateAt are legacy DATETIME
        (not DATETIME2). This table was evidently recreated by hand against
        prod at some point.
     8. dbo.ProjectAndBudget exists in production but has NO CREATE TABLE
        statement anywhere in init_db.sql — it's only referenced by an
        UPDATE ... RTRIM cleanup statement. Its structure below is captured
        purely from the live connection.
     9. Indexes documented in init_db.sql's "P0 performance indexes (added
        2026-05-12)" section — IX_worklogs_project, IX_users_status,
        IX_file_folders_parent_name, IX_worklogs_log_date — are NOT present
        on the live server that was inspected. Either db.init_db() has not
        run against this instance recently, or this is a different/older
        copy of the database than the one the Flask app targets. They are
        still created below (as the documented target design) but flagged
        inline.
    10. dbo.settings currently holds 2 rows in production, not the single
        'worklog_open' key init_db.sql seeds: 'worklog_open' is '1' (open),
        not '0' as init_db.sql's own seed default; and a second key,
        'failed_logins', holds a live JSON blob of per-username login-
        throttle bookkeeping (see app/auth.py). Neither is schema — the
        seed section below only creates the structural default key/value
        pair init_db.sql documents ('worklog_open' = '0'), matching
        intent, not current runtime state.

   SCHEMA: SQL Server resolves every unqualified table name against the
   login's default schema, which is "dbo" here — and 73 call sites across
   app/*.py (allowance.py, worklogs.py, employees.py, avatars.py, auth.py,
   members.py, users.py, skills.py, projects.py, exports.py) additionally
   hardcode an explicit "dbo." prefix on Employee/Allowance/ProjectAndBudget/
   holiday queries. To avoid rewriting those 73 call sites, every table here
   is created inside a real "dbo" schema (not "public") — see the
   `CREATE SCHEMA` / `SET search_path` lines right after BEGIN below. The
   Postgres role the app connects as must also have "dbo" on its
   search_path (e.g. `ALTER ROLE mwl_app SET search_path = dbo, public;`)
   so the unqualified queries continue to resolve too.

   DECISIONS SURFACED (not silently made — override if you disagree):
     - BIT → BOOLEAN. Idiomatic Postgres, but NOT a drop-in replacement:
       app/files.py:188-189 embeds raw, unparameterized SQL text like
       `' AND is_classified = 0'` — that literal `0` will fail against a
       real boolean column (`operator does not exist: boolean = integer`).
       Reading a boolean column back via psycopg2 as `bool` is fine
       everywhere else (e.g. allowance.py's `int(row['IsEditRow']) == 1`
       still works since `int(True) == 1`). Grep for `= 0` / `= 1` /
       `,0)` / `,1)` near is_classified / is_allowance / IsEditRow during
       the app port; a couple of spots need `= false` / `= true` instead.
       If you'd rather have zero app-layer diff for this specific column
       family, use SMALLINT (0/1) instead — every existing comparison and
       bound parameter keeps working unchanged, at the cost of losing
       Postgres's native boolean typing/CHECK-free true/false semantics.
     - CHAR(n) preserved as CHAR(n) (not VARCHAR(n)) on the tables where
       production is already CHAR/NCHAR (worklogs.Description, projects.
       Description, holiday.description, and every Allowance/
       ProjectAndBudget text column). This is literal fidelity to what's
       live today, but it re-imports the exact blank-padding class of bug
       that init_db.sql's own RTRIM backfill section exists to clean up —
       CHAR(n) blank-pads on read, which breaks naive `=` comparisons
       against trimmed input. Since none of these CHAR columns appear to
       be documented/load-bearing (they're absent from init_db.sql
       entirely — see drift notes above), VARCHAR(n) is arguably the
       correct call here precisely because the CHAR-ness is itself
       undocumented drift rather than an intentional design choice. Left
       as CHAR to match production exactly; swap to VARCHAR if you'd
       rather not carry the bug forward.

   NAMING: every identifier is double-quoted to preserve exact MSSQL casing
   (e.g. "EmployeeID", "CreateAt") 1:1, since that minimizes churn if/when
   application code is ported. Remember Postgres requires the exact same
   quoting on every reference in application SQL — unquoted "EmployeeID"
   folds to employeeid and will not match.

   SCOPE: schema only. Seed data mirrors the same minimal bootstrap rows
   init_db.sql inserts (one project, one legacy member, one admin user, one
   root file-share folder) — NOT a full data export of the 1,915 worklog
   rows / 25 employees / 25 users currently in production. Ask separately
   for a data-migration script (pg_dump-equivalent via ETL) if a full data
   copy is needed — exporting real employee/user PII belongs in its own
   reviewed step, not bundled into a structural migration script.

   VERIFIED ASSUMPTION: the "hours"/"overtime_hours"/"regular_hours"
   generated columns below translate MSSQL's DATEDIFF(MINUTE, a, b)
   (integer minute-boundaries-crossed) into EXTRACT(EPOCH FROM (b-a))/60.0
   (exact fractional minutes). These only agree if every stored start_time/
   end_time falls on a whole minute. Confirmed against the live server
   (2026-08-14):
     SELECT COUNT(*) FROM worklogs WHERE DATEPART(SECOND,start_time)<>0
       OR DATEPART(SECOND,end_time)<>0 OR DATEPART(NANOSECOND,start_time)<>0
       OR DATEPART(NANOSECOND,end_time)<>0;   -- returned 0
   If new sub-minute values are ever written, re-verify before trusting
   this migration's computed columns against production's.

   REQUIRES: PostgreSQL 12+ (GENERATED ALWAYS AS ... STORED generated
   columns) and PostgreSQL 10+ (GENERATED ... AS IDENTITY). Syntax-checked
   with sqlglot (postgres dialect) — parses clean, 29 statements. NOT yet
   exercised against a running Postgres engine in this environment (Docker
   Desktop was unavailable / slow to start here); before trusting the
   generated columns in production, run this against a real instance and
   insert one row with start_time='08:00', end_time='17:30' — expect
   hours=8.00, overtime_hours=0.00, regular_hours=8.00.
============================================================================ */

BEGIN;

-- SQL Server resolves every unqualified table name against "dbo" (the
-- login's default schema), and 73 call sites in app/*.py hardcode an
-- explicit "dbo." prefix (see the SCHEMA note above). Creating everything
-- inside a real "dbo" schema — instead of the Postgres default "public" —
-- means none of those call sites need to change.
CREATE SCHEMA IF NOT EXISTS dbo;
SET search_path TO dbo, public;

/* =========================
   MEMBERS (legacy, kept for FK compatibility — see CLAUDE.md §4)
========================= */
CREATE TABLE IF NOT EXISTS "members" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       VARCHAR(200) NOT NULL,
    "department" VARCHAR(100),
    "staff_id"   VARCHAR(50)
);

/* =========================
   EMPLOYEE (authoritative HR directory)
========================= */
CREATE TABLE IF NOT EXISTS "Employee" (
    "ID"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID"      VARCHAR(5)   NOT NULL,
    "EmployeeName"    VARCHAR(150) NOT NULL,
    "Department"      VARCHAR(100),
    "Position"        VARCHAR(100),
    "Level"           VARCHAR(10),
    "JG"              VARCHAR(20),
    "CreateAt"        TIMESTAMP DEFAULT now(),
    "UpdateAt"        TIMESTAMP DEFAULT now(),
    "AvatarPath"      VARCHAR(300),
    "AvatarMime"      VARCHAR(100),
    "AvatarUpdatedAt" TIMESTAMP,
    "Operation"       VARCHAR(100)  -- DRIFT: live-only column, absent from init_db.sql
);

/* =========================
   USERS (must precede security tables / self-FK on reviewed_by)
========================= */
CREATE TABLE IF NOT EXISTS "users" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"      VARCHAR(100) NOT NULL,
    "password_hash" VARCHAR(256) NOT NULL,
    "role"          VARCHAR(50)  NOT NULL DEFAULT 'Staff',
    "member_id"     INTEGER REFERENCES "members"("id"),
    -- DRIFT: INT in production; every other EmployeeID column in this schema
    -- (Employee, worklogs, member_skills) is a VARCHAR(5)/VARCHAR(10)
    -- business key. init_db.sql declares this as NVARCHAR(5). Preserved as
    -- INTEGER here to match the live connection exactly — flag for cleanup.
    "EmployeeID"    INTEGER,
    "status"        VARCHAR(20)  NOT NULL DEFAULT 'Active',
    "reviewed_by"   INTEGER REFERENCES "users"("id"),
    "reviewed_at"   TIMESTAMP DEFAULT now(),
    "created_at"    TIMESTAMP DEFAULT now(),
    "email"         VARCHAR(255),
    CONSTRAINT "UQ_users_username" UNIQUE ("username"),
    CONSTRAINT "CK_users_role"   CHECK ("role" IN ('Staff','Leader','Admin','Super_Ultimate_ADMIN')),
    CONSTRAINT "CK_users_status" CHECK ("status" IN ('Pending','Active','Declined'))
);

CREATE INDEX IF NOT EXISTS "IX_users_status" ON "users" ("status");
-- ^ documented in init_db.sql's 2026-05-12 P0 index batch but NOT present
--   on the live server inspected (see drift note #9 above).

/* =========================
   SECURITY TABLES
========================= */
CREATE TABLE IF NOT EXISTS "user_security_state" (
    "user_id"                    INTEGER PRIMARY KEY REFERENCES "users"("id"),
    "failed_login_count"         INTEGER NOT NULL DEFAULT 0,
    "failed_login_window_start"  TIMESTAMP,
    "locked_until"               TIMESTAMP,
    "unlock_token_hash"          VARCHAR(256),
    "unlock_token_expires_at"    TIMESTAMP,
    "last_unlock_email_sent_at"  TIMESTAMP,
    "updated_at"                 TIMESTAMP NOT NULL DEFAULT now(),
    "reset_token_hash"           VARCHAR(64),
    "reset_token_expires_at"     TIMESTAMP,
    "last_reset_email_sent_at"   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "security_events" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"    INTEGER REFERENCES "users"("id"),
    "username"   VARCHAR(100),
    "event_type" VARCHAR(100) NOT NULL,
    "ip_address" VARCHAR(100),
    "user_agent" VARCHAR(500),
    "detail"     TEXT,
    "created_at" TIMESTAMP DEFAULT now()
);

/* =========================
   PROJECTS
========================= */
CREATE TABLE IF NOT EXISTS "projects" (
    "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"            VARCHAR(200) NOT NULL,
    "main_members"    TEXT,   -- JSON array of EmployeeIDs, stored as text (see CLAUDE.md §4)
    "support_members" TEXT,
    "Description"     CHAR(500),  -- DRIFT: live-only column, absent from init_db.sql
    CONSTRAINT "UQ_projects_name" UNIQUE ("name")
);

/* =========================
   WORKLOGS
========================= */
CREATE TABLE IF NOT EXISTS "worklogs" (
    "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"         INTEGER REFERENCES "members"("id"),  -- legacy, kept NULL going forward
    "EmployeeID"        VARCHAR(5),                          -- authoritative post-migration
    "log_date"          DATE NOT NULL,
    "project"           VARCHAR(200),
    "ProjectDepartment" VARCHAR(20),   -- DRIFT: init_db.sql's ALTER declares NVARCHAR(100); live is NVARCHAR(20)
    "task"              VARCHAR(500),
    "start_time"        TIME,
    "end_time"          TIME,

    -- hours: (end - start) minus lunch overlap (12:00-13:00). Mirrors the
    -- MSSQL PERSISTED computed column using LEAST/GREATEST on TIME values.
    "hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL AND "end_time" >= "start_time"
            THEN (
                EXTRACT(EPOCH FROM ("end_time" - "start_time")) / 60.0
                - CASE
                    WHEN "start_time" < TIME '13:00:00' AND "end_time" > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '13:00:00') - GREATEST("start_time", TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            )::NUMERIC(5,2)
            ELSE NULL
        END
    ) STORED,

    -- overtime_hours: minutes before 08:30 plus minutes after 17:30.
    "overtime_hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL AND "end_time" >= "start_time"
            THEN (
                (CASE WHEN "start_time" < TIME '08:30:00'
                      THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '08:30:00') - "start_time")) / 60.0
                      ELSE 0 END)
                +
                (CASE WHEN "end_time" > TIME '17:30:00'
                      THEN EXTRACT(EPOCH FROM ("end_time" - GREATEST("start_time", TIME '17:30:00'))) / 60.0
                      ELSE 0 END)
            )::NUMERIC(5,2)
            ELSE NULL
        END
    ) STORED,

    -- DRIFT: NVARCHAR(100) live vs NVARCHAR(50) as originally declared.
    "status" VARCHAR(100),
    "note"   VARCHAR(1000),

    -- DRIFT: DECIMAL(18,2) live vs DECIMAL(5,2) as the ALTERs in init_db.sql declare.
    "OT1"   NUMERIC(18,2),
    "OT3"   NUMERIC(18,2),
    "OT1_5" NUMERIC(18,2),

    "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now(),

    "Description" CHAR(500),           -- DRIFT: CHAR(500) live vs NVARCHAR(500) declared
    "IsEditRow"   BOOLEAN DEFAULT TRUE, -- DRIFT: nullable live vs NOT NULL as declared

    -- regular_hours: portion of work inside 08:30-17:30 minus lunch overlap.
    "regular_hours" NUMERIC(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN "start_time" IS NOT NULL AND "end_time" IS NOT NULL
                 AND "end_time" > TIME '08:30:00' AND "start_time" < TIME '17:30:00'
            THEN (
                EXTRACT(EPOCH FROM (LEAST("end_time", TIME '17:30:00') - GREATEST("start_time", TIME '08:30:00'))) / 60.0
                - CASE
                    WHEN "start_time" < TIME '13:00:00' AND "end_time" > TIME '12:00:00'
                    THEN EXTRACT(EPOCH FROM (LEAST("end_time", TIME '13:00:00') - GREATEST("start_time", TIME '12:00:00'))) / 60.0
                    ELSE 0
                  END
            )::NUMERIC(5,2)
            ELSE 0
        END
    ) STORED,

    "is_allowance"       BOOLEAN NOT NULL DEFAULT FALSE,
    "allowance_overtime" NUMERIC(18,2) DEFAULT 0.00,  -- DRIFT: DECIMAL(18,2) live vs DECIMAL(5,2) declared

    -- DRIFT: live allows 'Leave' in addition to the 4 values init_db.sql documents.
    CONSTRAINT "CK_worklogs_status" CHECK ("status" IN ('Done','In Progress','Pending','Man day','Leave'))
);

CREATE INDEX IF NOT EXISTS "IX_worklogs_employee_date" ON "worklogs" ("EmployeeID", "log_date");

CREATE INDEX IF NOT EXISTS "IX_worklogs_project" ON "worklogs" ("project") WHERE "project" IS NOT NULL;
-- ^ documented in init_db.sql's 2026-05-12 P0 index batch but NOT present
--   on the live server inspected (see drift note #9 above).

CREATE INDEX IF NOT EXISTS "IX_worklogs_log_date" ON "worklogs" ("log_date", "EmployeeID", "project", "status");
-- ^ Postgres has no INCLUDE-vs-key distinction requirement here; listed as
--   a single composite index. Also absent on the live server inspected.

/* =========================
   MEMBER SKILLS
========================= */
CREATE TABLE IF NOT EXISTS "member_skills" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"  INTEGER,  -- FK to members(id) intentionally dropped post-migration (see init_db.sql history)
    "name"       VARCHAR(120) NOT NULL,
    "level"      SMALLINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
    "EmployeeID" VARCHAR(5),
    CONSTRAINT "CK_member_skills_level" CHECK ("level" BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS "IX_member_skills_employee" ON "member_skills" ("EmployeeID");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_member_skills_employee_name"
    ON "member_skills" ("EmployeeID", "name")
    WHERE "EmployeeID" IS NOT NULL;

/* =========================
   SETTINGS
========================= */
CREATE TABLE IF NOT EXISTS "settings" (
    "key"   VARCHAR(100) PRIMARY KEY,
    "value" TEXT NOT NULL
);

/* =========================
   FILE SHARE
========================= */
CREATE TABLE IF NOT EXISTS "file_folders" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(200) NOT NULL,
    "parent_id"     INTEGER REFERENCES "file_folders"("id"),
    "created_by"    INTEGER REFERENCES "users"("id"),
    "created_at"    TIMESTAMP DEFAULT now(),
    "is_classified" BOOLEAN NOT NULL DEFAULT FALSE,  -- DRIFT: live-only column, absent from init_db.sql (backs CLAUDE.md §7b classified-file gating)
    CONSTRAINT "UQ_file_folders_parent_name" UNIQUE ("parent_id", "name")
);

CREATE INDEX IF NOT EXISTS "IX_file_folders_parent_name" ON "file_folders" ("parent_id", "name");
-- ^ documented in init_db.sql but not present live (redundant with the
--   UNIQUE constraint's own index) — see drift note #9.

CREATE TABLE IF NOT EXISTS "files" (
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "folder_id"     INTEGER REFERENCES "file_folders"("id"),
    "original_name" VARCHAR(400) NOT NULL,
    "stored_name"   VARCHAR(200) NOT NULL,  -- UUID-based; never user input
    "size_bytes"    BIGINT NOT NULL,
    "mime_type"     VARCHAR(200),
    "sha256"        CHAR(64),
    "uploaded_by"   INTEGER REFERENCES "users"("id"),
    "uploaded_at"   TIMESTAMP DEFAULT now(),
    "is_classified" BOOLEAN NOT NULL DEFAULT FALSE,  -- DRIFT: live-only column, absent from init_db.sql
    CONSTRAINT "UQ_files_stored_name" UNIQUE ("stored_name")
);

CREATE INDEX IF NOT EXISTS "IX_files_folder" ON "files" ("folder_id");

/* =========================
   HOLIDAY
   DRIFT (see note #6): live "ID" has no IDENTITY/auto-increment, "date" is
   nullable with no UNIQUE constraint, and "description" is CHAR(200) not
   NVARCHAR(500). All three preserved as-is below to match production.
========================= */
CREATE TABLE IF NOT EXISTS "holiday" (
    "ID"          INTEGER PRIMARY KEY,  -- no auto-increment live; inserts must supply an explicit ID
    "date"        DATE,
    "description" CHAR(200)
);

/* =========================
   ALLOWANCE
   DRIFT (see note #7): this table was evidently recreated by hand against
   production and no longer matches init_db.sql's declared CREATE TABLE at
   all. Columns/types below are taken purely from the live connection.
========================= */
CREATE TABLE IF NOT EXISTS "Allowance" (
    "ID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "log_date"    DATE DEFAULT CURRENT_DATE,
    "EmployeeID"  CHAR(5),
    "ProjectCode" CHAR(30),
    "Description" CHAR(500),
    "type"        CHAR(1),
    "CreateAt"    TIMESTAMP DEFAULT now(),
    "UpdateAt"    TIMESTAMP DEFAULT now(),
    "IsEditRow"   BOOLEAN DEFAULT TRUE
);

/* =========================
   PROJECT AND BUDGET
   DRIFT (see note #8): no CREATE TABLE for this exists anywhere in
   init_db.sql — captured purely from the live connection.
========================= */
CREATE TABLE IF NOT EXISTS "ProjectAndBudget" (
    "ID"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectCode"       CHAR(50),
    "Budget"            CHAR(50),
    "Description"       CHAR(500),
    "CreateAt"          TIMESTAMP DEFAULT now(),
    "UpdateAt"          TIMESTAMP DEFAULT now(),
    "Status"            VARCHAR(20) DEFAULT 'Initiative',
    "ProjectDepartment" VARCHAR(20)
);

/* =========================
   SEED DATA
   Mirrors the same minimal bootstrap rows init_db.sql inserts. Idempotent
   via ON CONFLICT. Does NOT copy live production data (25 employees, 25
   users, 1,915 worklog rows currently on the inspected server) — see the
   SCOPE note at the top of this file.
========================= */
INSERT INTO "projects" ("name")
VALUES ('Warehouse')
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "members" ("name", "department")
SELECT 'Boonyarith Akkarasongthum', 'Meter'
WHERE NOT EXISTS (SELECT 1 FROM "members" WHERE "name" = 'Boonyarith Akkarasongthum');

INSERT INTO "users" ("username", "password_hash", "role", "status", "EmployeeID")
VALUES (
    'sultadkukkuk',
    'scrypt:32768:8:1$6BpoyyNeineDbHF7$ab9ef6ceb57ba1a3bebe67b798313a149be239686efbe3a622421b287884b61232151accc1ee2b30bed04b6a85e688ab65544354fb434bad28641d650e01145d',
    'Super_Ultimate_ADMIN', 'Active', 11111
)
ON CONFLICT ("username") DO NOTHING;

INSERT INTO "file_folders" ("name", "parent_id")
SELECT 'Shared', NULL
WHERE NOT EXISTS (SELECT 1 FROM "file_folders" WHERE "parent_id" IS NULL AND "name" = 'Shared');

INSERT INTO "settings" ("key", "value")
VALUES ('worklog_open', '0')
ON CONFLICT ("key") DO NOTHING;

COMMIT;
